
foo: foo12
democonfigclient:
    message: hello spring io

server:
  port: 8882

spring:
  
  application:
    name: config-client
    
  cloud:
    stream:
      default-binder: kafka
    config:
      label: master
      profile: dev2
      #uri:
        #- http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
    bus:
      trace:
        enabled: true
      enabled: true
      refresh:
        enabled: true
      #id: ${spring.application.name}:${spring.cloud.config.profile}:${random.value}
      
  kafka:
    bootstrap-servers:
      - 192.168.1.102:9092
      - 192.168.1.103:9092
      - 192.168.1.104:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.103:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    
    
logging: 
  config: classpath:logback-spring-dev2.xml
  
